# Generated by Django 4.1.7 on 2023-05-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField(max_length=50)),
                ('q2', models.TextField(max_length=50)),
                ('q3', models.CharField(max_length=50)),
                ('q4', models.CharField(max_length=50)),
                ('q5', models.CharField(max_length=50)),
            ],
        ),
    ]
